### ISSUE TITLE
zeal integration[feature request]

### ISSUE THREAD

**Issue by ahxxm** [chao787/DealM#13]
[zeal](https://github.com/jinzhu/zeal-at-point) is a Dash(offline documentation lookup software) alternative for Windows and Linux

In-system doc might be more efficient than tab switching?

**Comment by chao787** [comment]
Better to use `C-c d` to find specific doc per mode.
No clue why we need zeal integration.

No windows and linux machine means it's hard for me to integrate it correctly.

PR accepted. and you can replace it with some shortcut key (reuse dash-at-point.el) with a system checking condition.
