### ISSUE TITLE
F2 grep changes window height when split vertically

### ISSUE THREAD

**Issue by ahxxm** [chao787/DealM#18]
OSX 10.12.1 + iterm2 3.0.11 + latest emacs and dealm

the height of result window will not be the same as source window... almost cured my OCD

**Comment by chao787** [comment]
Can you just provide more info here?
for ex: bash, zsh, and versions??

**Comment by ahxxm** [comment]
.... can't easily reproduce

a dirty fix for me is C-x 1 + C-x 2
