### ISSUE TITLE
tomorrow-night theme not found

### ISSUE THREAD

**Issue by ahxxm** [chao787/DealM#2]
theme-settings.el will try to `(load-theme 'tomorrow-night t)` from `plugins/emacs-color-theme-solarized/`, but no tomorrow-night there.

> ➜  emacs-color-theme-solarized git:(553ce32) ls -lw
> total 128
> -rw-r--r--  1 orz  staff   1061 Sep 10 23:45 LICENSE
> -rw-r--r--  1 orz  staff   8672 Sep 10 23:45 README.md
> -rw-r--r--  1 orz  staff    109 Sep 10 23:45 color-theme-solarized-pkg.el
> -rw-r--r--  1 orz  staff   1846 Sep 10 23:45 color-theme-solarized.el
>  -rwxr-xr-x  1 orz  staff    309 Sep 10 23:45 makepkg.sh
> -rw-r--r--  1 orz  staff    169 Sep 10 23:45 solarized-dark-theme.el
> -rw-r--r--  1 orz  staff  28386 Sep 10 23:45 solarized-definitions.el
> -rw-r--r--  1 orz  staff    170 Sep 10 23:45 solarized-light-theme.el

**Comment by ahxxm** [comment]
Emacs file:

> ➜  emacs-color-theme-solarized git:(553ce32) cat ~/.emacs
> (load-file '"/Users/guoxuda/dev/DealM/emacs-dealM.el")

Environment: OS X 10.10.5 + Emacs-24.5-1-universal.dmg downloaded from [here](http://emacsformacosx.com/)

**Comment by ahxxm** [comment]
> Submodule path 'snippets': checked out '9d4074e76f8bb745bd0089e8f0d915a56b20fafe'
> Unable to checkout '879c8fc37173d4bc2ca9c2041b98b99eb68ee894' in submodule path 'python-lib'

**Comment by ahxxm** [comment]
> File error: Cannot open load file, no such file or directory, ggtags-settings

**Comment by chao787** [comment]
> Submodule path 'snippets': checked out '9d4074e76f8bb745bd0089e8f0d915a56b20fafe'
> Unable to checkout '879c8fc37173d4bc2ca9c2041b98b99eb68ee894' in submodule path 'python-lib'

still cannot checkout python-lib?

**Comment by ahxxm** [comment]
no i can't

**Comment by chao787** [comment]
## reference:

- 2e1b703401e8426b3e768e081f9fc967fa4bef74
- 9b530e4dd25b10dc56dd878ea85e2ef0ab203643
- e1fca93d490da0d31b8279bffaa61e2da0a6eaaf
