### ISSUE TITLE
F1 slow

### ISSUE THREAD

**Issue by ahxxm** [chao787/DealM#27]
seems it will traverse project directory recursively for a file list *every* time F1 is pressed..

**Comment by chao787** [comment]
Sorry but please add more details, cannot reproduce the slow senario.

**Comment by ahxxm** [comment]
old machine with HDD, open emacs in [this](https://github.com/chao787/DealM) or [kernel](https://github.com/torvalds/linux) repo, press F1

**Comment by chao787** [comment]
in the git repo. We use the `projectile-find-file` de facto. please refer `projectile-find-file` in repo https://github.com/bbatsov/projectile
