### ISSUE TITLE
Require associated-with-github-account pubkey to do submodule update

### ISSUE THREAD

**Issue by ahxxm** [chao787/DealM#3]
or it will fail because `git@github.com`, message:

Cloning into 'plugins/ac-nrepl'...
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:purcell/ac-nrepl.git' into submodule path 'plugins/ac-nrepl' failed

**Comment by chao787** [comment]
Yes, you are right. I should use `https://` for better support.

**Comment by chao787** [comment]
you can pull master now and do a  `git submodule sync` to fix this problem. :8ball:

**Comment by ahxxm** [comment]
> Cloning into 'plugins/ac-nrepl'...
> fatal: repository 'https://github.com:purcell/ac-nrepl.git/' not found
> Clone of 'https://github.com:purcell/ac-nrepl.git' into submodule path 'plugins/ac-nrepl' failed

**Comment by ahxxm** [comment]
seems `.gitmodules` does not read `:` as `/` .. 

I've substituted them [here](https://gist.githubusercontent.com/ahxxm/f0c253dd87debb6fb6e0/raw/981cf7bfb16da371fd9d78bf52629163392ac6dd/.gitmodule)
