### ISSUE TITLE
auto space does not work as expected, and causes syntax error

### ISSUE THREAD

**Issue by ahxxm** [chao787/DealM#4]
In C++ mode, when I have this code:

`for (int p = 1; p`

and type the following`!=2`, it will become:

`for (int p = 1; p! = 2`

**Comment by ahxxm** [comment]
`std::string a;`

when I want to define a reference to `a`:

`int`

then `space` + `&ar`, it become:

`int& ar`

**Comment by ahxxm** [comment]
`main` + `tab` result in ... 

```
int main(int argc, char *argv[])
{

  return 0;
}
```
I think the first `{` should be at the end of first line?

**Comment by chao787** [comment]
> main + tab result in ...
> 
> int main(int argc, char *argv[])
> {
> 
>   return 0;
> }
> I think the first { should be at the end of first line?

one issue one ticket pls. :8ball:

**Comment by ahxxm** [comment]
too lazy to open another issue /w\

**Comment by chao787** [comment]
> std::string a;
> 
> when I want to define a reference to a:
> 
> int
> 
> then space + &ar, it become:
> 
> int& ar

this is also a FIXME from https://github.com/xwl/electric-spacing/blob/master/electric-spacing.el#L247
please make PR to that repo.

**Comment by chao787** [comment]
> std::string a;
> 
> when I want to define a reference to a:
> 
> int
> 
> then space + &ar, it become:
> 
> int& ar

I give a temp solution in efaf6a21f3916a3e2cc77d5e9a4962c9ef5c0681 for char &i
At least we can ensure the keep the ` &` behave correctly
