### ISSUE TITLE
class snippet error in c++ mode

### ISSUE THREAD

**Issue by ahxxm** [chao787/DealM#6]
here's symptom:

![image](https://cloud.githubusercontent.com/assets/1286225/12481118/eabdd788-c081-11e5-810f-01b3d96e34a2.png)

reproduce: type `class`, then type `tab`

**Comment by chao787** [comment]
the text is deprecated and removed since emacs 24.3 I guess.
Will fix it soon.

**Comment by chao787** [comment]
fixed in 88e0905ae2cb43fb76185d62533b63c799fdc0a9

**Comment by ahxxm** [comment]
but .gitmodules didn't update  ...
