### ISSUE TITLE
startup speed too slow

### ISSUE THREAD

**Issue by ahxxm** [chao787/DealM#7]
takes about 80 seconds to start now, after disable `lisp-settings` time it drops to 3 seconds. but then emacs will fail to open file..

**Comment by ahxxm** [comment]
`tramp` is causing this problem, it is dependency of `cider`, and will spawn an ssh process using command `/usr/bin/ssh -o ControlPath=%C host.does.not.exist`..

for some reason my dns resolves this domain to an ip address which does not respond ping(i guess it drops packages).

workaround: (http://emacs.stackexchange.com/questions/18438/emacs-suspend-at-startup-ssh-connection-issue)[http://emacs.stackexchange.com/questions/18438/emacs-suspend-at-startup-ssh-connection-issue]

**Comment by chao787** [comment]
Do you mind to create a PR for this issue, because I cannot reproduce this.
